### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by mattboyce2000** [thycotic/arc-docs#3]
Document: (https://docs.thycotic.com/ss-arc/1.0.0/secret-server/distributed-engines/index.md)

https://docs.thycotic.com/ss-arc/1.0.0/networking/ssh-proxy-configuration/index.md Within the document goes nowhere. Is it also possible to have an RDP proxy variant of this?

**Comment by danigran** [comment]
This has been addressed with the latest update to the files.
